- build.gradle
> [AK] update assertj to latest

- build.gradle
> [AK] add files to exclude from sonar scan

- Dockerfile
- web.config
> [AK] modify webconfig

- src/main/java/uk/gov/hmcts/reform/workallocation/controllers/RootController.java
- web.config
> Pr testing

- README.md
- build.gradle
> [AK] Modify readme

- Jenkinsfile_CNP
- charts/ctsc-work-allocation/Chart.yaml
- charts/ctsc-work-allocation/values.aat.template.yaml
- charts/ctsc-work-allocation/values.preview.template.yaml
- charts/ctsc-work-allocation/values.yaml
- src/main/resources/bootstrap.yaml
> [AK] move s2s key to helm chart

- Jenkinsfile_CNP
- charts/ctsc-work-allocation/Chart.yaml
- charts/ctsc-work-allocation/values.aat.template.yaml
- charts/ctsc-work-allocation/values.preview.template.yaml
- charts/ctsc-work-allocation/values.yaml
- src/main/resources/bootstrap.yaml
> [AK] use terraform to get service key

- charts/ctsc-work-allocation/Chart.yaml
> [AK] bump helm chart version

- build.gradle
- src/main/java/uk/gov/hmcts/reform/workallocation/config/AppConfig.java
- src/main/java/uk/gov/hmcts/reform/workallocation/services/CcdPollingService.java
- src/main/java/uk/gov/hmcts/reform/workallocation/services/LastRunTimeService.java
- src/main/java/uk/gov/hmcts/reform/workallocation/util/TaskErrorHandler.java
- src/test/java/uk/gov/hmcts/reform/workallocation/service/CcdPollingServiceTest.java
> [AK] fine tune transaction handling

- charts/ctsc-work-allocation/values.preview.template.yaml
- src/main/java/uk/gov/hmcts/reform/workallocation/model/Task.java
- src/main/java/uk/gov/hmcts/reform/workallocation/services/CcdConnectorService.java
- src/main/java/uk/gov/hmcts/reform/workallocation/services/CcdPollingService.java
- src/test/java/uk/gov/hmcts/reform/workallocation/model/TaskTest.java
- src/test/java/uk/gov/hmcts/reform/workallocation/service/CcdConnectionServiceTest.java
- src/test/java/uk/gov/hmcts/reform/workallocation/service/CcdPollingServiceTest.java
> [AK] filter es result only to what fields we are interested

- build.gradle
> [AK] bump lib versions

- src/main/java/uk/gov/hmcts/reform/workallocation/services/EmailSendingService.java
> [AK] fix production ccd deep-link-url

- build.gradle
- charts/ctsc-work-allocation/values.yaml
- src/main/java/uk/gov/hmcts/reform/workallocation/services/CcdConnectorService.java
> [AK] change probate query to include registryLocation

- build.gradle
- dependency-check-suppressions.xml
> [AK] bump versions

- build.gradle
- dependency-check-suppressions.xml
> [AK] collection of version bumps

- build.gradle
- charts/ctsc-work-allocation/values.preview.template.yaml
- dependency-check-suppressions.xml
> [AK] version updates

- README.md
- build.gradle
- dependency-check-suppressions.xml
- src/main/java/uk/gov/hmcts/reform/workallocation/services/CcdPollingService.java
- src/main/resources/application.yaml
> Transaction handling fix

- build.gradle
- dependency-check-suppressions.xml
- infrastructure/main.tf
> [AK] bump version

- Jenkinsfile_CNP
- build.gradle
- dependency-check-suppressions.xml
- gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/CTSCT-9
Remove installcharts to fix pipeline, update spring-boot, postgresql driver & gradlew and suppress dependency warnings
> Fix pr build

- infrastructure/main.tf
> Use local merged tags

- .gitignore
- Jenkinsfile_CNP
- build.gradle
- src/smokeTest/java/uk/gov/hmcts/reform/workallocation/SmokeTest.java
- src/test/java/uk/gov/hmcts/reform/workallocation/RootControllerTest.java
- src/test/java/uk/gov/hmcts/reform/workallocation/data/migration/FlywayNoOpStrategyTest.java
- src/test/java/uk/gov/hmcts/reform/workallocation/email/TaskVelocityContextTest.java
- src/test/java/uk/gov/hmcts/reform/workallocation/email/VelocityContextFactoryTest.java
- src/test/java/uk/gov/hmcts/reform/workallocation/model/AuditLogTest.java
- src/test/java/uk/gov/hmcts/reform/workallocation/model/TaskTest.java
- src/test/java/uk/gov/hmcts/reform/workallocation/queue/BaseQueueConsumerTest.java
- src/test/java/uk/gov/hmcts/reform/workallocation/queue/DeadQueueConsumerTest.java
- src/test/java/uk/gov/hmcts/reform/workallocation/queue/DelayedExecutorTest.java
- src/test/java/uk/gov/hmcts/reform/workallocation/queue/QueueConsumerTest.java
- src/test/java/uk/gov/hmcts/reform/workallocation/queue/QueueProducerTest.java
- src/test/java/uk/gov/hmcts/reform/workallocation/service/CcdConnectionServiceTest.java
- src/test/java/uk/gov/hmcts/reform/workallocation/service/CcdPollingServiceTest.java
- src/test/java/uk/gov/hmcts/reform/workallocation/service/DummyEmailSendingServiceTest.java
https://tools.hmcts.net/jira/browse/CTSCT-17
Add serenity report
```
[ ] Yes
[X] No
```
> CTSCT-17: Add serenity report

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/CTSCT-28
Fixing postgres jar upgrade issue
```
[ ] Yes
[ x] No
```
> CTSCT-28: Fixing postgres jar upgrade

- src/main/java/uk/gov/hmcts/reform/workallocation/services/EmailSendingService.java
https://tools.hmcts.net/jira/browse/DTSBPS-156
Showing ExUI task URL in Case workers' email for from work allocation
```
[ ] Yes
[X ] No
```
> Ctsct 52 exui url change demo

- build.gradle
- src/main/java/uk/gov/hmcts/reform/workallocation/queue/QueueProducer.java
- src/test/java/uk/gov/hmcts/reform/workallocation/queue/QueueProducerTest.java
DTSBPS-236
Bump azure-servicebus from 3.4.0 to 3.5.0
```
[ ] Yes
[ X] No
```
> DTSBPS-236: Bump azure service bus

- charts/ctsc-work-allocation/Chart.yaml
- charts/ctsc-work-allocation/requirements.yaml
https://tools.hmcts.net/jira/browse/DTSBPS-244
update-chart-version
```
[ ] Yes
[x ] No
```
> DTSBPS-244: update-chart-version

- dependency-check-suppressions.xml
Fixed dependency check
Fixed dependency check
```
[ ] Yes
[ X] No
```
> Fixed dependency check

- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/DTSBPS-341
Adding nightly build
```
[ ] Yes
[ X] No
```
> adding nightly build

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSBPS-346
```
[ ] Yes
[X ] No
```
> DTSBPS-346: dependency-check-suppressions update

- build.gradle
https://tools.hmcts.net/jira/browse/DTSBPS-367
Upgrade spring boot version 2.3.5.RELEASE to 2.4.2
```
[ ] Yes
[ X] No
```
> bump spring boot 2.4.2

- src/main/java/uk/gov/hmcts/reform/workallocation/queue/QueueConsumer.java
https://tools.hmcts.net/jira/browse/DTSBPS-395
Stop WA for probate
```
[ ] Yes
[ X] No
```
> DTSBPS-395 Stopping task poller for Probate

- build.gradle
- src/main/java/uk/gov/hmcts/reform/workallocation/queue/QueueConsumer.java
- src/main/java/uk/gov/hmcts/reform/workallocation/services/CcdConnectorService.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/workallocation/service/CcdConnectorServiceTest.java
https://tools.hmcts.net/jira/browse/DTSBPS-423
Disable probate ES Query as probate is not being used.
```
[ ] Yes
[ X] No
```
> DTSBPS-423: Disable probate ES query

- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSBPS-439
Fix for Published Vulnerabilities 
```
[ ] Yes
[X ] No
```
> DTSBPS-439 Fix for Published Vulnerabilities

- build.gradle
https://tools.hmcts.net/jira/browse/DTSBPS-461
1. Bump applicationinsights-logging-logback from 2.6.2 to 2.6.3 
2. Bump applicationinsights-spring-boot-starter from 2.6.2 to 2.6.3
3. Bump flyway-core from 7.7.0 to 7.7.1 
4. Bump org.flywaydb.flyway from 7.7.0 to 7.7.1
5. Bump guava from 30.1-jre to 30.1.1-jre
```
[ ] Yes
[ X] No
```
> DTSBPS-461: bump dependencies

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSBPS-478
Dependencies check io.netty group
Bump io.freefair.lombo
Removed outdated suppression
```
[ ] Yes
[ X] No
```
> DTSBPS-478: Dependencies check io.netty group

- dependency-check-suppressions.xml
added Published Vulnerabilities suppression CVE-2021-29425
```
[ ] Yes
[X ] No
```
> Fix nightly build
